-- V1.0__create_codon_table.sql
CREATE TABLE codon_table (
    id SERIAL PRIMARY KEY, 
    codon TEXT UNIQUE NOT NULL,
    amino_acid_name TEXT NOT NULL,
    three_letter_code TEXT,
    one_letter_code TEXT,
    is_start BOOLEAN DEFAULT FALSE, 
    is_stop BOOLEAN DEFAULT FALSE  
);

-- Insert codon mappings
INSERT INTO codon_table (codon, amino_acid_name, three_letter_code, one_letter_code, is_start, is_stop) VALUES
('UUU', 'Phenylalanine', 'Phe', 'F', FALSE, FALSE),
('UUC', 'Phenylalanine', 'Phe', 'F', FALSE, FALSE),
('UUA', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('UUG', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('UCU', 'Serine', 'Ser', 'S', FALSE, FALSE),
('UCC', 'Serine', 'Ser', 'S', FALSE, FALSE),
('UCA', 'Serine', 'Ser', 'S', FALSE, FALSE),
('UCG', 'Serine', 'Ser', 'S', FALSE, FALSE),
('UAU', 'Tyrosine', 'Tyr', 'Y', FALSE, FALSE),
('UAC', 'Tyrosine', 'Tyr', 'Y', FALSE, FALSE),
('UAA', 'Stop', 'Stop', '*', FALSE, TRUE),
('UAG', 'Stop', 'Stop', '*', FALSE, TRUE),
('UGU', 'Cysteine', 'Cys', 'C', FALSE, FALSE),
('UGC', 'Cysteine', 'Cys', 'C', FALSE, FALSE),
('UGA', 'Stop', 'Stop', '*', FALSE, TRUE),
('UGG', 'Tryptophan', 'Trp', 'W', FALSE, FALSE),
('CUU', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('CUC', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('CUA', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('CUG', 'Leucine', 'Leu', 'L', FALSE, FALSE),
('CCU', 'Proline', 'Pro', 'P', FALSE, FALSE),
('CCC', 'Proline', 'Pro', 'P', FALSE, FALSE),
('CCA', 'Proline', 'Pro', 'P', FALSE, FALSE),
('CCG', 'Proline', 'Pro', 'P', FALSE, FALSE),
('CAU', 'Histidine', 'His', 'H', FALSE, FALSE),
('CAC', 'Histidine', 'His', 'H', FALSE, FALSE),
('CAA', 'Glutamine', 'Gln', 'Q', FALSE, FALSE),
('CAG', 'Glutamine', 'Gln', 'Q', FALSE, FALSE),
('CGU', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('CGC', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('CGA', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('CGG', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('AUU', 'Isoleucine', 'Ile', 'I', FALSE, FALSE),
('AUC', 'Isoleucine', 'Ile', 'I', FALSE, FALSE),
('AUA', 'Isoleucine', 'Ile', 'I', FALSE, FALSE),
('AUG', 'Methionine', 'Met', 'M', TRUE, FALSE),
('ACU', 'Threonine', 'Thr', 'T', FALSE, FALSE),
('ACC', 'Threonine', 'Thr', 'T', FALSE, FALSE),
('ACA', 'Threonine', 'Thr', 'T', FALSE, FALSE),
('ACG', 'Threonine', 'Thr', 'T', FALSE, FALSE),
('AAU', 'Asparagine', 'Asn', 'N', FALSE, FALSE),
('AAC', 'Asparagine', 'Asn', 'N', FALSE, FALSE),
('AAA', 'Lysine', 'Lys', 'K', FALSE, FALSE),
('AAG', 'Lysine', 'Lys', 'K', FALSE, FALSE),
('AGU', 'Serine', 'Ser', 'S', FALSE, FALSE),
('AGC', 'Serine', 'Ser', 'S', FALSE, FALSE),
('AGA', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('AGG', 'Arginine', 'Arg', 'R', FALSE, FALSE),
('GUU', 'Valine', 'Val', 'V', FALSE, FALSE),
('GUC', 'Valine', 'Val', 'V', FALSE, FALSE),
('GUA', 'Valine', 'Val', 'V', FALSE, FALSE),
('GUG', 'Valine', 'Val', 'V', FALSE, FALSE),
('GCU', 'Alanine', 'Ala', 'A', FALSE, FALSE),
('GCC', 'Alanine', 'Ala', 'A', FALSE, FALSE),
('GCA', 'Alanine', 'Ala', 'A', FALSE, FALSE),
('GCG', 'Alanine', 'Ala', 'A', FALSE, FALSE),
('GAU', 'Aspartic acid', 'Asp', 'D', FALSE, FALSE),
('GAC', 'Aspartic acid', 'Asp', 'D', FALSE, FALSE),
('GAA', 'Glutamic acid', 'Glu', 'E', FALSE, FALSE),
('GAG', 'Glutamic acid', 'Glu', 'E', FALSE, FALSE),
('GGU', 'Glycine', 'Gly', 'G', FALSE, FALSE),
('GGC', 'Glycine', 'Gly', 'G', FALSE, FALSE),
('GGA', 'Glycine', 'Gly', 'G', FALSE, FALSE),
('GGG', 'Glycine', 'Gly', 'G', FALSE, FALSE);